--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BestCodrEver/LobbyPlayerLimit
build-by-default: true
branches:
- main
projects:
  LobbyPlayerLimit:
    path: ""
    icon: "icon.jpg"
...
