name: LobbyPlayerLimit
author: BestCodrEver
main: BestCodrEver\LobbyPlayerLimit\Main
version: 1.1.1
api: 3.0.0

commands:
 lobby:
  description: "Teleport to a lobby"
  usage: /lobby
  permission: lobbyplayerlimit.lobby

permissions:
 lobbyplayerlimit.lobby:
  description: "Allows a player to teleport to lobby"
  default: true 
